#开发环境
server:
  port: 8081

spring:
  #mysql数据库配置
  datasource:
    url: jdbc:mysql://192.168.2.2:3306/manager
    username: root
    password: root
  #redis数据库配置
  redis:
    host: 192.168.2.2
    port: 6379
    password: 123456
    database: 0
    timeout: 2000ms
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
  #JPA配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none